package com.skennedy.lazuli.typebinding;

public enum BoundExpressionType {

    ARRAY_ACCESS_EXPRESSION,
    ARRAY_LENGTH_EXPRESSION,
    ARRAY_LITERAL_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    BINARY_EXPRESSION,
    BINARY_OPERATOR,
    BLOCK,
    CONDITIONAL_GOTO,
    FOR,
    FOR_IN,
    FUNCTION_CALL,
    FUNCTION_ARGUMENT,
    FUNCTION_DECLARATION,
    MATCH_EXPRESSION,
    MATCH_CASE_EXPRESSION,
    GOTO,
    IF,
    LABEL,
    LITERAL,
    NOOP,
    RETURN,
    PRINT_INTRINSIC,
    TYPEOF_INTRINSIC,
    VARIABLE_DECLARATION,
    VARIABLE_EXPRESSION,
    WHILE


}
