package com.skennedy.lazuli.parsing.model;

public enum ExpressionType {

    ARRAY_ACCESS_EXPR,
    ARRAY_ASSIGNMENT_EXPR,
    ARRAY_DECLARATION_EXPR,
    ARRAY_LEN_EXPR,
    ARRAY_LITERAL_EXPR,
    ASSIGNMENT_EXPR,
    BINARY_EXPR,
    BLOCK_EXPR,
    FOR_EXPR,
    FOR_IN_EXPR,
    FUNC_ARG_EXPR,
    FUNC_CALL_EXPR,
    FUNC_DECLARATION_EXPR,
    IDENTIFIER_EXPR,
    IF_EXPR,
    IMPORT,
    INCREMENT_EXPR,
    LAMBDA_EXPRESSION,
    LITERAL_EXPR,
    MAP_EXPRESSION,
    MATCH_CASE_EXPRESSION,
    MATCH_EXPRESSION,
    MEMBER_ACCESSOR_EXPR,
    NAMESPACE,
    NAMESPACE_ACCESSOR_EXPR,
    PARENTHESISED_EXPR,
    PRINT_EXPR,
    RANGE_EXPR,
    RETURN_EXPR,
    STRUCT_DECLARATION_EXPR,
    TUPLE_LITERAL_EXPR,
    TYPEOF_EXPR,
    TYPE_EXPR,
    UNARY_EXPR,
    VAR_DECLARATION_EXPR,
    WHILE_EXPR,
    YIELD_EXPRESSION


}
